### ISSUE TITLE
No proper handling for multiple conf.d

### ISSUE THREAD

**Issue by gbirke** [silpion/ansible-php#1]
On Ubuntu 14.4 and PHP 5.5 there is no common `/etc/php5/conf.d` file. Instead there is a `conf.d` directory for each usage (`cli`, `cgi`, etc). On a fresh Vagrant machine, the install fails.

In the current solution, I can only configure cgi by setting the `php_confd` variable to `/etc/php5/cgi/conf.d/`. Could you change this to be an array (in the tasks and in the default config) to accommodate for multiple `conf.d`?

**Comment by ghost** [comment]
Hey,

Anja provided some commits to this issue. Unfortunately I felt the need to force push on master, because of issues with moving some remotes. Hope these commits fix the issue, hope the force push doesn't annoys anyone too much.
